version: '3'

services:
  ci-build:
    image: mcr.microsoft.com/dotnet/core/aspnet:3.1
    command: /bin/bash -c "dotnet restore ./ContainerWebApp.sln && dotnet publish ./ContainerWebApp.sln -c Debug -o ./obj/Docker/publish"
